import {readdir,readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const root=new URL('../',import.meta.url),pkg=JSON.parse(await readFile(new URL('package.json',root)));
async function walk(directory){const result=[];for(const file of await readdir(new URL(directory,root),{withFileTypes:true})){const path=directory+file.name;if(file.isDirectory())result.push(...await walk(path+'/'));else if(!/LICENSE|OFL|versions\.json|\.txt$/i.test(path))result.push(path);}return result;}
const shell=['index.html','app.js','app.css','receipt.js','reading.js','stamp-renderer.js','ocr.js','export-file.js','counters.js','pdf-import.js','image-processing.js','image-tools.js','image-worker.js','document-analysis.js','pdf-export.js','local-store.js','receipt-viewer.js','offline.js','manifest.webmanifest'];
const paths=[...shell,...await walk('assets/'),...await walk('vendor/')].sort();
const assets=await Promise.all(paths.map(async path=>{const bytes=await readFile(new URL(path,root));return {path,size:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')};}));
await writeFile(new URL('offline-assets.js',root),'// Generated by npm run build:offline. Do not edit.\nself.STAMPFEL_OFFLINE = '+JSON.stringify({version:pkg.version,assets},null,2)+';\n');
console.log(`${assets.length} offline assets, ${(assets.reduce((sum,a)=>sum+a.size,0)/1048576).toFixed(1)} MiB, v${pkg.version}`);
